name: Playwright Tests
on: [push, pull_request] # Triggers on code push or PR

jobs:
  test:
    runs-on: ubuntu-latest # Use GitHub's Ubuntu machine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Match your local Node version

      - name: Install dependencies
        run: npm ci # Clean install (faster than `npm install`)

      - name: Install Playwright browsers
        run: npx playwright install --with-deps # Install browsers like Chromium

      - name: Run Playwright tests
        run: npx playwright test # Run all tests

      - name: Upload HTML report
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/